platform :ios, '11.0'
use_frameworks!

target 'TestApp' do
  pod 'webfunny_otel_ios_crashreporting', '~> 0.0.2'
  pod 'webfunny_otel_ios', '~> 0.0.2'
#  pod 'webfunny_otel_ios', :path=> '/Users/huangkai/Documents/Develop/webfunny_otel_ios'
end
